// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dashboard struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	DeviceTotal  int    `json:"deviceTotal"`
	RunningTotal int    `json:"runningTotal"`
	ErrorTotal   int    `json:"errorTotal"`
}

type DashboardDevice struct {
	ID        int      `json:"id"`
	Number    string   `json:"number"`
	Status    string   `json:"status"`
	Total     int      `json:"total"`
	Ng        int      `json:"ng"`
	Durations []int    `json:"durations"`
	Errors    []string `json:"errors"`
}

type DashboardWrap struct {
	Total      int          `json:"total"`
	Dashboards []*Dashboard `json:"dashboards"`
}
